version: '2'
services:
    cinematics-app:
        image: cinematics
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://cinematics-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=cinematics
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cinematics-mongodb:
        extends:
            file: mongodb.yml
            service: cinematics-mongodb
